---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lhsqc542/public_html/
    - /bin/rsync -av --delete --exclude='*.db' --exclude='*.sqlite' --exclude='LHSQC-*.php' /home/lhsqc542/repo_lhsqc/public_html/ $DEPLOYPATH/
